### ISSUE TITLE
Error 01

### ISSUE THREAD

**Issue by AfolayanOduntan012** [Ljthendy13/Animal-Arithmatics#4]
I recently debugged the code and found some error in the C# Script 
The pic to where to find the error is below

<img width="960" alt="2024-12-03_14h21_09" src="https://github.com/user-attachments/assets/da93035c-a6ff-437c-939e-1b4a35be4751">

**Comment by Ljthendy13** [comment]
This is not an error, you must install the "TextMesh Pro" package in Unity in order to run this program in engine, this error would not occur in build.
